name: Build, Push and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-app
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy-to-cluster:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Minikube
        uses: manusa/actions-setup-minikube@v2
        with:
          minikube version: 'latest'
          kubernetes version: 'v1.26.0'
          driver: docker
          container-runtime: containerd

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          minikube kubectl -- config view --flatten > $HOME/.kube/config
          kubectl config use-context minikube
          kubectl cluster-info
          kubectl get nodes

      - name: Validate manifests
        run: kubectl apply -f k8s/ --dry-run=client

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Verify deployment
        run: |
          kubectl get pods -o wide
          kubectl get svc
          minikube service list